version: "3.2"
services:
  php:
    build: 
      context: .
    image: oliverp83/php-mysql-demo
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_USER=seleguin
      - MYSQL_PASSWORD=S3l3gu1n@#
      - MYSQL_DB=solicitan_info
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:80"
    container_name: php-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=seleguin
      - MYSQL_PASSWORD=S3l3gu1n@# 
      - MYSQL_DATABASE=solicitan_info
    container_name: mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-app
networks:
  frontend:
  backend: