version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.319.3-jdk11
    ports:
      - 8080:8080
    container_name: jenkins
    user: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker